---
title: "LT: ioslidesでwebスライド作成"
output:
  revealjs::revealjs_presentation:
    theme: solarized
    transition: slide
    self_contained: false
    reveal_options:
      slideNumber: true
      previewLinks: true
    reveal_plugins: ["chalkboard", "menu"]
subtitle: "Japan.R 2024"
date: "Published:2024-11-14, Last Update(JST): `r format(Sys.time(), '%Y-%m-%d %X')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 自己紹介

### 寺井雅人

- 所属：愛知工科大学（助教）
- 研究：心理実験を行い、反応測度などを統計モデルで分析。
- R歴：2018年～現在に至る
- X: [\@uniquefreshman](https://twitter.com/uniquefreshman)
- .Rとの出会い: 2018年の名古屋大でのNagoya.R

## 話したい事

- 簡単に分析ファイルをスライド資料に変えられるioslidesがある
- その結果コピペや表の数字の写し作業チェックから解放
- おそらくあと4分もないから早口です
- 今回の詳しい内容はこちら：[Qiita](https://qiita.com/masato-terai)

## ioslidesとは
- ここに説明を書く

# スライドの作り方

## 準備するもの
- R markdownファイル

## やり方
- YAMLヘッダーを変更

```{markdown}         
title: "Untitled"
output: ioslides_presentation
date: "2024-04-15"
```

-   **\#**で定義するレベル分けでスライドの区切りが代わる

    -   **\#**でスライドのセクション見出し
    -   **\##**で新しいページ
    -   **\###**ページ内の太文字

-   枠にとらわれない！

    -   以下のチャンクを先頭に入れると、スクロール可能なスライドになる（チャンク内はrではなく、`=html`にする）。
    -   注意点として、タッチパッドや、マウスホイールでスクロールできますが、スクロールバーを掴んでスクロールはできません。

```{markdown}         
<style>
  slides > slide {
    overflow-x: auto !important;
    overflow-y: auto !important;
}
</style>
```

## その他の細かい設定
- スライドの移行スピード
    - default, slower, faster
```{markdown}         
title: "LT: ioslidesでwebスライド作成"
#output: html_document
output:
  ioslides_presentation:
    transition: slower
```

# 最後に
- もう少し細かい設定をするなら```Reveal.js```
- このスライドはReveal.jsです。
-- transitionやtheme、その他にも様々な設定ができます。
-- Rmdからのスライド作成であれば、ioslidesから入ればOK?
-- 学会発表などであればioslidesがシンプルでよさそう
- LTの時間では紹介しきれない！

# Reference
- https://codingclubuc3m.rbind.io/post/2019-09-24/
- https://github.com/rstudio/revealjs

# Ref for reveal.js
- https://revealjs.com/themes/

# Note
10-20ページ
floreパッケージでハイライトを行う